- name: copy file
  copy:
    src: /root/redis-5.0.8.tar
    dest: /opt/

- name: tar -xvf
  unarchive:
    src: /opt/redis-5.0.8.tar
    dest: /opt/
    remote_src: yes

- name: mv folder
  shell: mv /opt/redis-5.0.8 /opt/redis

- name: creat folder log
  file:
    path: /var/log/redis
    state: directory

- name: install redis
  shell: |
    cd /opt/redis
    make
- name: file system redis-server
  template:
    src: redis-server.service.j2
    dest: /usr/lib/systemd/system/redis-server.service

- name: systemd redis-sentinel
  template:
    src: redis-sentinel.service.j2
    dest: /usr/lib/systemd/system/redis-sentinel.service

- name: copy file redis.conf
  template:
    src: redisserver.conf.j2
    dest: /opt/redis/redis.conf
  notify: start_redis-server

- name: copy file sentinel
  template:
    src: sentinel.conf.j2
    dest: /opt/redis/sentinel.conf

- name: file system redis-server
  template:
    src: redis-server.service.j2
    dest: /usr/lib/systemd/system/redis-server.service
  notify: start_redis-sentinel



